### PR TITLE
Missing "fi" for respective "if" in install.sh

### PR DESCRIPTION
**Pull request by vatsalchandan**
One "fi" was missing and it was giving error while installing via run ./install.sh

### CODE REVIEW

**Comment by KhushrajRathod** [comment]
Hi, thanks for making a PR.
The 'fi' was supposed to be in the place of else

**Comment by KhushrajRathod** [comment]
If you've already pushed the IMS apk, and you're on a version less then v216, you'll want to run

```
adb shell setprop persist.dbg.allow_ims_off 1
adb shell setprop persist.dbg.volte_avail_ovr 1
adb shell setprop persist.dbg.vt_avail_ovr 1
adb shell setprop persist.dbg.wfc_avail_ovr 1
adb shell setprop persist.sys.phh.ims.caf true
```

**Comment by vatsalchandan** [comment]
> Hi, thanks for making a PR.
> The 'fi' was supposed to be in the place of else

Oh sorry, I couldn't get whole flow so mistake for place of 'fi'.

**Comment by vatsalchandan** [comment]
> If you've already pushed the IMS apk, and you're on a version less then v216, you'll want to run
> 
> ```
> adb shell setprop persist.dbg.allow_ims_off 1
> adb shell setprop persist.dbg.volte_avail_ovr 1
> adb shell setprop persist.dbg.vt_avail_ovr 1
> adb shell setprop persist.dbg.wfc_avail_ovr 1
> adb shell setprop persist.sys.phh.ims.caf true
> ```

Actually I tried zip method via twrp but it didn't worked for me,

Where should be these props situated ? in system/build.prop or vendor/build.prop 

I checked both place but they were not in these both places, and I also couldn't find ims.apk in system/pri-app

Device: Oneplus 7
Rom: Descedant X A/B gsi

**Comment by KhushrajRathod** [comment]
Hi,
The props wouldn't be in system/build.prop and vendor/build.prop. To check if you've successfully set the props, run

```
getprop persist.dbg.allow_ims_off
getprop persist.dbg.volte_avail_ovr
getprop persist.dbg.vt_avail_ovr
getprop persist.dbg.wfc_avail_ovr
getprop persist.sys.phh.ims.caf
```

The ims apk should be located here: /system/priv-app/ims/ims.apk
Note that the 64bit ims apk is possibly broken, I will be publishing v3 of VoLTE-Fix soon, please wait for that

**Comment by KhushrajRathod** [comment]
If you have further problems, please open a new issue

**Pull request merged**
